// This file will be auto-generated by: npx supabase gen types typescript
// For now, it serves as a placeholder with manual type definitions
// matching the schema in supabase/migrations/00001_initial_schema.sql

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type CharacterClass = "warrior" | "mage" | "healer" | "scout";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string;
          role: "teacher" | "student";
          level: number;
          total_xp: number;
          max_hp: number;
          avatar_url: string | null;
          character_class: CharacterClass | null;
          dyslexia_font_enabled: boolean;
          high_contrast_enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name: string;
          role?: "teacher" | "student";
          level?: number;
          total_xp?: number;
          max_hp?: number;
          avatar_url?: string | null;
          character_class?: CharacterClass | null;
          dyslexia_font_enabled?: boolean;
          high_contrast_enabled?: boolean;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      templates: {
        Row: {
          id: string;
          teacher_id: string;
          boss_name: string;
          boss_avatar_id: string;
          questions: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          teacher_id: string;
          boss_name: string;
          boss_avatar_id?: string;
          questions: Json;
        };
        Update: Partial<Database["public"]["Tables"]["templates"]["Insert"]>;
      };
      sessions: {
        Row: {
          id: string;
          template_id: string;
          teacher_id: string;
          battle_code: string;
          expected_student_count: number;
          status: "waiting" | "active" | "paused" | "completed";
          created_at: string;
          started_at: string | null;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          template_id: string;
          teacher_id: string;
          battle_code: string;
          expected_student_count: number;
          status?: "waiting" | "active" | "paused" | "completed";
        };
        Update: Partial<Database["public"]["Tables"]["sessions"]["Insert"]>;
      };
      session_participants: {
        Row: {
          id: string;
          session_id: string;
          student_id: string;
          character_class: CharacterClass | null;
          current_question_index: number;
          damage_dealt: number;
          xp_earned: number;
          joined_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          student_id: string;
          character_class?: CharacterClass | null;
          current_question_index?: number;
          damage_dealt?: number;
          xp_earned?: number;
        };
        Update: Partial<
          Database["public"]["Tables"]["session_participants"]["Insert"]
        >;
      };
      classrooms: {
        Row: {
          id: string;
          teacher_id: string;
          name: string;
          invite_token: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          teacher_id: string;
          name: string;
          invite_token?: string;
        };
        Update: Partial<Database["public"]["Tables"]["classrooms"]["Insert"]>;
      };
      classroom_students: {
        Row: {
          id: string;
          classroom_id: string;
          student_id: string;
          joined_at: string;
        };
        Insert: {
          id?: string;
          classroom_id: string;
          student_id: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["classroom_students"]["Insert"]
        >;
      };
      classroom_groups: {
        Row: {
          id: string;
          classroom_id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          classroom_id: string;
          name: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["classroom_groups"]["Insert"]
        >;
      };
      classroom_group_members: {
        Row: {
          id: string;
          group_id: string;
          student_id: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          student_id: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["classroom_group_members"]["Insert"]
        >;
      };
      session_state: {
        Row: {
          session_id: string;
          current_boss_hp: number;
          max_boss_hp: number;
          current_question_index: number;
          logs: Json;
          updated_at: string;
        };
        Insert: {
          session_id: string;
          current_boss_hp: number;
          max_boss_hp: number;
          current_question_index?: number;
          logs?: Json;
        };
        Update: Partial<
          Database["public"]["Tables"]["session_state"]["Insert"]
        >;
      };
    };
    Functions: {
      deal_damage: {
        Args: {
          p_session_id: string;
          p_student_id: string;
          p_damage: number;
          p_xp_reward: number;
          p_log_entry: Json;
        };
        Returns: { new_boss_hp: number; boss_defeated: boolean }[];
      };
      generate_battle_code: {
        Args: Record<string, never>;
        Returns: string;
      };
      get_classroom_by_token: {
        Args: { p_token: string };
        Returns: { id: string; name: string }[];
      };
      get_session_by_battle_code: {
        Args: { p_battle_code: string };
        Returns: {
          id: string;
          template_id: string;
          teacher_id: string;
          battle_code: string;
          expected_student_count: number;
          status: string;
          current_boss_hp: number | null;
          max_boss_hp: number | null;
        }[];
      };
      is_session_participant: {
        Args: { p_session_id: string };
        Returns: boolean;
      };
    };
  };
}
